// js/monsters_img.js
// Estruturas globais para mapear nome do monstro (name_en) para ícones e ovos
// Assumindo:
// - Ícones de Monstros: assets/monster_icons/NOME.webp
// - Ícones de Ovos: assets/monster_eggs/NOME.svg

/**
 * Mapeamento de nome do monstro (name_en) para o caminho do arquivo de ícone.
 */
const monster_icons = {
    // A maioria dos nomes de arquivo .webp corresponde ao nome_en, exceto minérios/bugs
    "Agnaktor": "monster_icons/Agnaktor.webp",
    "Altaroth": "monster_icons/Altaroth.webp",
    "Anjanath": "monster_icons/Anjanath.webp",
    "Apceros": "monster_icons/Apceros.webp",
    "Aptonoth": "monster_icons/Aptonoth.webp",
    "Arzuros": "monster_icons/Arzuros.webp",
    "Ash Kecha Wacha": "monster_icons/Ash Kecha Wacha.webp",
    "Astalos": "monster_icons/Astalos.webp",
    "Azure Rathalos": "monster_icons/Azure Rathalos.webp",
    "Baggi": "monster_icons/Baggi.webp",
    "Barioth": "monster_icons/Barioth.webp",
    "Barroth": "monster_icons/Barroth.webp",
    "Basarios": "monster_icons/Basarios.webp",
    "Bazelgeuse": "monster_icons/Bazelgeuse.webp",
    "Black Diablos": "monster_icons/Black Diablos.webp",
    "Black Gravios": "monster_icons/Black Gravios.webp",
    "Bloodbath Diablos": "monster_icons/Bloodbath Diablos.webp",
    "Blue Yian Kut-Ku": "monster_icons/Blue Yian Kut-Ku.webp",
    "Bnahabra (Blue)": "monster_icons/Bnahabra (Blue).webp",
    "Bnahabra (Brown)": "monster_icons/Bnahabra (Brown).webp",
    "Bnahabra (Green)": "monster_icons/Bnahabra (Green).webp",
    "Bnahabra (Red)": "monster_icons/Bnahabra (Red).webp",
    "Boltreaver Astalos": "monster_icons/Boltreaver Astalos.webp",
    "Brachydios": "monster_icons/Brachydios.webp",
    "Brute Tigrex": "monster_icons/Brute Tigrex.webp",
    "Bulldrome": "monster_icons/Bulldrome.webp",
    "Bullfango": "monster_icons/Bullfango.webp",
    "Cephadrome": "monster_icons/Cephadrome.webp",
    "Cephalos": "monster_icons/Cephalos.webp",
    "Conga": "monster_icons/Conga.webp",
    "Congalala": "monster_icons/Congalala.webp",
    "Crimson Qurupeco": "monster_icons/Crimson Qurupeco.webp",
    "Daimyo Hermitaur": "monster_icons/Daimyo Hermitaur.webp",
    "Desert Seltas Queen": "monster_icons/Desert Seltas Queen.webp",
    "Deviljho": "monster_icons/Deviljho.webp",
    "Diablos": "monster_icons/Diablos.webp",
    "Dreadking Rathalos": "monster_icons/Dreadking Rathalos.webp",
    "Dreadqueen Rathian": "monster_icons/Dreadqueen Rathian.webp",
    "Duramboros": "monster_icons/Duramboros.webp",
    "Elderfrost Gammoth": "monster_icons/Elderfrost Gammoth.webp",
    "Emerald Congalala": "monster_icons/Emerald Congalala.webp",
    "Fatalis": "monster_icons/_Unknown.webp",
    "Fulgur Anjanath": "monster_icons/Fulgur Anjanath.webp",
    "Gammoth": "monster_icons/Gammoth.webp",
    "Gargwa": "monster_icons/Gargwa.webp",
    "Gendrome": "monster_icons/Gendrome.webp",
    "Genprey": "monster_icons/Genprey.webp",
    "Glacial Agnaktor": "monster_icons/Glacial Agnaktor.webp",
    "Glavenus": "monster_icons/Glavenus.webp",
    "Gold Rathian": "monster_icons/Gold Rathian.webp",
    "Gravios": "monster_icons/Gravios.webp",
    "Great Baggi": "monster_icons/Great Baggi.webp",
    "Great Jaggi": "monster_icons/Great Jaggi.webp",
    "Great Thunderbug": "monster_icons/Great Thunderbug.webp",
    "Green Nargacuga": "monster_icons/Green Nargacuga.webp",
    "Green Plesioth": "monster_icons/Green Plesioth.webp",
    "Grimclaw Tigrex": "monster_icons/Grimclaw Tigrex.webp",
    "Gypceros": "monster_icons/Gypceros.webp",
    "Hellblade Glavenus": "monster_icons/Hellblade Glavenus.webp",
    "Hermitaur": "monster_icons/Hermitaur.webp",
    "Iodrome": "monster_icons/Iodrome.webp",
    "Ioprey": "monster_icons/Ioprey.webp",
    "Ivory Lagiacrus": "monster_icons/Ivory Lagiacrus.webp",
    "Jade Barroth": "monster_icons/Jade Barroth.webp",
    "Jaggi": "monster_icons/Jaggi.webp",
    "Jaggia": "monster_icons/Jaggia.webp",
    "Kecha Wacha": "monster_icons/Kecha Wacha.webp",
    "Kelbi": "monster_icons/Kelbi.webp",
    "Khezu": "monster_icons/Khezu.webp",
    "Kirin": "monster_icons/Kirin.webp",
    "Konchu (Blue)": "monster_icons/Konchu (Blue).webp",
    "Konchu (Green)": "monster_icons/Konchu (Green).webp",
    "Konchu (Red)": "monster_icons/Konchu (Red).webp",
    "Konchu (Yellow)": "monster_icons/Konchu (Yellow).webp",
    "Kulu-Ya-Ku": "monster_icons/Kulu-Ya-Ku.webp",
    "Kulve Taroth": "monster_icons/Kulve Taroth.webp",
    "Kushala Daora": "monster_icons/Kushala Daora.webp",
    "Lagiacrus": "monster_icons/Lagiacrus.webp",
    "Lagombi": "monster_icons/Lagombi.webp",
    "Larinoth": "monster_icons/Larinoth.webp",
    "Legiana": "monster_icons/Legiana.webp",
    "Ludroth": "monster_icons/Ludroth.webp",
    "Mizutsune": "monster_icons/Mizutsune.webp",
    "Molten Tigrex": "monster_icons/Molten Tigrex.webp",
    "Monoblos": "monster_icons/Monoblos.webp",
    "Nargacuga": "monster_icons/Nargacuga.webp",
    "Nergigante": "monster_icons/Nergigante.webp",
    "Nerscylla": "monster_icons/Nerscylla.webp",
    "Oroshi Kirin": "monster_icons/Oroshi Kirin.webp",
    "Paolumu": "monster_icons/Paolumu.webp",
    "Pink Rathian": "monster_icons/Pink Rathian.webp",
    "Plesioth": "monster_icons/Plesioth.webp",
    "Plum Daimyo Hermitaur": "monster_icons/Plum Daimyo Hermitaur.webp",
    "Popo": "monster_icons/Popo.webp",
    "Pukei-Pukei": "monster_icons/Pukei-Pukei.webp",
    "Purple Gypceros": "monster_icons/Purple Gypceros.webp",
    "Purple Ludroth": "monster_icons/Purple Ludroth.webp",
    "Qurupeco": "monster_icons/Qurupeco.webp",
    "Rajang": "monster_icons/Rajang.webp",
    "Rathalos": "monster_icons/Rathalos.webp",
    "Rathian": "monster_icons/Rathian.webp",
    "Red Khezu": "monster_icons/Red Khezu.webp",
    "Remobra": "monster_icons/Remobra.webp",
    "Royal Ludroth": "monster_icons/Royal Ludroth.webp",
    "Ruby Basarios": "monster_icons/Ruby Basarios.webp",
    "Sand Barioth": "monster_icons/Sand Barioth.webp",
    "Seltas": "monster_icons/Seltas.webp",
    "Seltas Queen": "monster_icons/Seltas Queen.webp",
    "Seregios": "monster_icons/Seregios.webp",
    "Shrouded Nerscylla": "monster_icons/Shrouded Nerscylla.webp",
    "Silver Rathalos": "monster_icons/Silver Rathalos.webp",
    "Silverwind Nargacuga": "monster_icons/Silverwind Nargacuga.webp",
    "Slagtoth (Brown)": "monster_icons/Slagtoth (Brown).webp",
    "Slagtoth (Green)": "monster_icons/Slagtoth (Green).webp",
    "Soulseer Mizutsune": "monster_icons/Soulseer Mizutsune.webp",
    "Stygian Zinogre": "monster_icons/Stygian Zinogre.webp",
    "Teostra": "monster_icons/Teostra.webp",
    "Tetsucabra": "monster_icons/Tetsucabra.webp",
    "Thunderlord Zinogre": "monster_icons/Thunderlord Zinogre.webp",
    "Tigrex": "monster_icons/Tigrex.webp",
    "Tobi-Kadachi": "monster_icons/Tobi-Kadachi.webp",
    "Uragaan": "monster_icons/Uragaan.webp",
    "Uroktor": "monster_icons/Uroktor.webp",
    "Velkhana": "monster_icons/Velkhana.webp",
    "Velocidrome": "monster_icons/Velocidrome.webp",
    "Velociprey": "monster_icons/Velociprey.webp",
    "Vespoid": "monster_icons/Vespoid.webp",
    "White Monoblos": "monster_icons/White Monoblos.webp",
    "Yian Garuga": "monster_icons/Yian Garuga.webp",
    "Yian Kut-Ku": "monster_icons/Yian Kut-Ku.webp",
    "Zamite": "monster_icons/Zamite.webp",
    "Zamtrios": "monster_icons/Zamtrios.webp",
    "Zinogre": "monster_icons/Zinogre.webp"
};

/**
 * Mapeamento de nome do monstro (name_en) para o nome e caminho do ovo.
 * Usa 'file: ""' para monstros que não têm ovo de Monstie.
 */
const monster_eggs = {
    // Monstro | Nome do Ovo | Caminho do Arquivo (SVG)
    "Agnaktor": { name: "Agnaktor", file: "" },
    "Anjanath": { name: "Anjanath", file: "monster_eggs/Anjanath.svg" },
    "Arzuros": { name: "Arzuros", file: "monster_eggs/Arzuros.svg" },
    "Astalos": { name: "Astalos", file: "monster_eggs/Astalos.svg" },
    "Azure Rathalos": { name: "Rathalos Lazúli", file: "monster_eggs/Azure Rathalos.svg" },
    "Barioth": { name: "Barioth", file: "monster_eggs/Barioth.svg" },
    "Barroth": { name: "Barroth", file: "monster_eggs/Barroth.svg" },
    "Basarios": { name: "Basarios", file: "monster_eggs/Basarios.svg" },
    "Bazelgeuse": { name: "Bazelgeuse", file: "monster_eggs/Bazelgeuse.svg" },
    "Black Diablos": { name: "Diablos Negra", file: "monster_eggs/Black Diablos.svg" },
    "Black Gravios": { name: "Gravios Tétrico", file: "monster_eggs/Black Gravios.svg" },
    "Bloodbath Diablos": { name: "Diablos Carnificina", file: "monster_eggs/Bloodbath Diablos.svg" },
    "Blue Yian Kut-Ku": { name: "Yian Kut-Ku Azul", file: "monster_eggs/Blue Yian Kut-Ku.svg" },
    "Boltreaver Astalos": { name: "Astalos Ceifarraios", file: "monster_eggs/Boltreaver Astalos.svg" },
    "Brachydios": { name: "Brachydios", file: "monster_eggs/Brachydios.svg" },
    "Brute Tigrex": { name: "Tigrex Bruto", file: "monster_eggs/Brute Tigrex.svg" },
    "Cephadrome": { name: "Cephadrome", file: "monster_eggs/Cephadrome.svg" },
    "Congalala": { name: "Congalala", file: "monster_eggs/Congalala.svg" },
    "Crimson Qurupeco": { name: "Qurupeco Rubro", file: "monster_eggs/Crimson Qurupeco.svg" },
    "Daimyo Hermitaur": { name: "Hermitauro Daimyo", file: "" },
    "Desert Seltas Queen": { name: "Rainha Seltas do Deserto", file: "" },
    "Deviljho": { name: "Deviljho", file: "monster_eggs/Deviljho.svg" },
    "Diablos": { name: "Diablos", file: "monster_eggs/Diablos.svg" },
    "Dreadking Rathalos": { name: "Rathalos Maldito", file: "monster_eggs/Dreadking Rathalos.svg" },
    "Dreadqueen Rathian": { name: "Rathian Maldita", file: "monster_eggs/Dreadqueen Rathian.svg" },
    "Duramboros": { name: "Duramboros", file: "" },
    "Elderfrost Gammoth": { name: "Gammoth Glaciarcaico", file: "monster_eggs/Elderfrost Gammoth.svg" },
    "Emerald Congalala": { name: "Congalala Esmeralda", file: "monster_eggs/Emerald Congalala.svg" },
    "Fatalis": { name: "Fatalis", file: "" },
    "Fulgur Anjanath": { name: "Anjanath Fulgurante", file: "monster_eggs/Fulgur Anjanath.svg" },
    "Gammoth": { name: "Gammoth", file: "monster_eggs/Gammoth.svg" },
    "Gendrome": { name: "Gendrome", file: "monster_eggs/Gendrome.svg" },
    "Glacial Agnaktor": { name: "Agnaktor Glacial", file: "" },
    "Glavenus": { name: "Glavenus", file: "monster_eggs/Glavenus.svg" },
    "Gold Rathian": { name: "Rathian Dourada", file: "monster_eggs/Gold Rathian.svg" },
    "Gravios": { name: "Gravios", file: "monster_eggs/Gravios.svg" },
    "Great Baggi": { name: "Grande Baggi", file: "monster_eggs/Great Baggi.svg" },
    "Great Jaggi": { name: "Grande Jaggi", file: "monster_eggs/Great Jaggi.svg" },
    "Green Nargacuga": { name: "Nargacuga Verde", file: "monster_eggs/Green Nargacuga.svg" },
    "Grimclaw Tigrex": { name: "Tigrex Ceifagarra", file: "monster_eggs/Grimclaw Tigrex.svg" },
    "Gypceros": { name: "Gypceros", file: "monster_eggs/Gypceros.svg" },
    "Hellblade Glavenus": { name: "Glavenus Flâmina", file: "monster_eggs/Hellblade Glavenus.svg" },
    "Iodrome": { name: "Iodrome", file: "monster_eggs/Iodrome.svg" },
    "Ivory Lagiacrus": { name: "Lagiacrus Marfim", file: "monster_eggs/Ivory Lagiacrus.svg" },
    "Jade Barroth": { name: "Barroth Jade", file: "monster_eggs/Jade Barroth.svg" },
    "Kecha Wacha": { name: "Kecha Wacha", file: "monster_eggs/Kecha Wacha.svg" },
    "Khezu": { name: "Khezu", file: "monster_eggs/Khezu.svg" },
    "Kirin": { name: "Kirin", file: "monster_eggs/Kirin.svg" },
    "Kulu-Ya-Ku": { name: "Kulu-Ya-Ku", file: "monster_eggs/Kulu-Ya-Ku.svg" },
    "Kushala Daora": { name: "Kushala Daora", file: "monster_eggs/Kushala Daora.svg" },
    "Lagiacrus": { name: "Lagiacrus", file: "monster_eggs/Lagiacrus.svg" },
    "Lagombi": { name: "Lagombi", file: "monster_eggs/Lagombi.svg" },
    "Legiana": { name: "Legiana", file: "monster_eggs/Legiana.svg" },
    "Mizutsune": { name: "Mizutsune", file: "monster_eggs/Mizutsune.svg" },
    "Molten Tigrex": { name: "Tigrex Ardente", file: "monster_eggs/Molten Tigrex.svg" },
    "Monoblos": { name: "Monoblos", file: "monster_eggs/Monoblos.svg" },
    "Nargacuga": { name: "Nargacuga", file: "monster_eggs/Nargacuga.svg" },
    "Nergigante": { name: "Nergigante", file: "monster_eggs/Nergigante.svg" },
    "Nerscylla": { name: "Nerscylla", file: "monster_eggs/Nerscylla.svg" },
    "Oroshi Kirin": { name: "Kirin Oroshi", file: "monster_eggs/Oroshi Kirin.svg" },
    "Paolumu": { name: "Paolumu", file: "monster_eggs/Paolumu.svg" },
    "Pink Rathian": { name: "Rathian Rosa", file: "monster_eggs/Pink Rathian.svg" },
    "Plesioth": { name: "Plesioth", file: "" },
    "Pukei-Pukei": { name: "Pukei-Pukei", file: "monster_eggs/Pukei-Pukei.svg" },
    "Purple Gypceros": { name: "Gypceros Púrpura", file: "monster_eggs/Purple Gypceros.svg" },
    "Purple Ludroth": { name: "Ludroth Púrpura", file: "monster_eggs/Purple Ludroth.svg" },
    "Qurupeco": { name: "Qurupeco", file: "monster_eggs/Qurupeco.svg" },
    "Rajang": { name: "Rajang", file: "monster_eggs/Rajang.svg" },
    "Rathalos": { name: "Rathalos", file: "monster_eggs/Rathalos.svg" },
    "Rathian": { name: "Rathian", file: "monster_eggs/Rathian.svg" },
    "Red Khezu": { name: "Khezu Rubro", file: "monster_eggs/Red Khezu.svg" },
    "Royal Ludroth": { name: "Ludroth Real", file: "monster_eggs/Royal Ludroth.svg" },
    "Ruby Basarios": { name: "Basarios Rubi", file: "monster_eggs/Ruby Basarios.svg" },
    "Sand Barioth": { name: "Barioth de Areia", file: "monster_eggs/Sand Barioth.svg" },
    "Seregios": { name: "Seregios", file: "monster_eggs/Seregios.svg" },
    "Shrouded Nerscylla": { name: "Nerscylla Sombria", file: "monster_eggs/Shrouded Nerscylla.svg" },
    "Silver Rathalos": { name: "Rathalos Prateado", file: "monster_eggs/Silver Rathalos.svg" },
    "Silverwind Nargacuga": { name: "Nargacuga Argentasa", file: "monster_eggs/Silverwind Nargacuga.svg" },
    "Soulseer Mizutsune": { name: "Mizutsune Vatealma", file: "monster_eggs/Soulseer Mizutsune.svg" },
    "Stygian Zinogre": { name: "Zinogre Tenebroso", file: "monster_eggs/Stygian Zinogre.svg" },
    "Teostra": { name: "Teostra", file: "monster_eggs/Teostra.svg" },
    "Thunderlord Zinogre": { name: "Zinogre Feralâmpago", file: "monster_eggs/Thunderlord Zinogre.svg" },
    "Tigrex": { name: "Tigrex", file: "monster_eggs/Tigrex.svg" },
    "Tobi-Kadachi": { name: "Tobi-Kadachi", file: "monster_eggs/Tobi-Kadachi.svg" },
    "Uragaan": { name: "Uragaan", file: "monster_eggs/Uragaan.svg" },
    "Velkhana": { name: "Velkhana", file: "monster_eggs/Velkhana.svg" },
    "Velocidrome": { name: "Velocídrome", file: "monster_eggs/Velocidrome.svg" },
    "White Monoblos": { name: "Monoblos Alvo", file: "monster_eggs/White Monoblos.svg" },
    "Yian Garuga": { name: "Yian Garuga", file: "monster_eggs/Yian Garuga.svg" },
    "Yian Kut-Ku": { name: "Yian Kut-Ku", file: "monster_eggs/Yian Kut-Ku.svg" },
    "Zamtrios": { name: "Zamtrios", file: "monster_eggs/Zamtrios.svg" },
    "Zinogre": { name: "Zinogre", file: "monster_eggs/Zinogre.svg" },

    // Monstros sem ovo (Não-Monsties)
    "Altaroth": { name: "Sem Ovo", file: "" },
    "Apceros": { name: "Sem Ovo", file: "" },
    "Aptonoth": { name: "Sem Ovo", file: "" },
    "Baggi": { name: "Sem Ovo", file: "" },
    "Bulldrome": { name: "Bulldrome", file: "monster_eggs/Bulldrome.svg" },
    "Bullfango": { name: "Sem Ovo", file: "" },
    "Cephalos": { name: "Sem Ovo", file: "" },
    "Conga": { name: "Sem Ovo", file: "" },
    "Great Thunderbug": { name: "Sem Ovo", file: "" },
    "Hermitaur": { name: "Sem Ovo", file: "" },
    "Jaggi": { name: "Sem Ovo", file: "" },
    "Jaggia": { name: "Sem Ovo", file: "" },
    "Kelbi": { name: "Sem Ovo", file: "" },
    "Konchu (Blue)": { name: "Sem Ovo", file: "" },
    "Konchu (Green)": { name: "Sem Ovo", file: "" },
    "Konchu (Red)": { name: "Sem Ovo", file: "" },
    "Konchu (Yellow)": { name: "Sem Ovo", file: "" },
    "Kulve Taroth": { name: "Sem Ovo", file: "" },
    "Larinoth": { name: "Sem Ovo", file: "" },
    "Ludroth": { name: "Sem Ovo", file: "" },
    "Popo": { name: "Sem Ovo", file: "" },
    "Remobra": { name: "Sem Ovo", file: "" },
    "Slagtoth (Brown)": { name: "Sem Ovo", file: "" },
    "Slagtoth (Green)": { name: "Sem Ovo", file: "" },
    "Uroktor": { name: "Sem Ovo", file: "" },
    "Velociprey": { name: "Sem Ovo", file: "" },
    "Vespoid": { name: "Sem Ovo", file: "" },
    "Ioprey": { name: "Sem Ovo", file: "" },
    "Zamite": { name: "Sem Ovo", file: "" }
};